# Generated by Django 4.2.7 on 2023-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='release_year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=1200),
        ),
    ]
