# Generated by Django 4.2.7 on 2023-12-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_year_movie_release_year_remove_movie_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=105),
        ),
    ]
