# Generated by Django 4.2.7 on 2023-12-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.CharField(max_length=4),
        ),
    ]
